### ISSUE TITLE
Gobber 2 Compatibility

### ISSUE THREAD

**Issue by Riazamurai** [Low-Orbit-Studios/Weaponworks#67]
I love your mod so much that I want you to be able to craft 
weapons in this mod with ores that are added in gobber

Gobber
https://www.curseforge.com/minecraft/mc-mods/gobber

**Comment by CallyKoh** [comment]
We are adding it to the list of mods for compatibility now, thank you for your support and suggestion :)

**Comment by Riazamurai** [comment]
That's good, I'm looking forward to the future development
